### ISSUE TITLE
[Security] Potential Secret Leak

### ISSUE THREAD

**Issue by raima-zachariah** [tianrluo/MRphy.py#1]
It has been noticed that while using codecov/codecov-action@v1.0.3 your token 5a0c6ffd-6377-42e2-8cce-bfa76e6f4f83 is present in plaintext. Please ensure that secrets are encrypted or not passed as plain text in github workflows.

**Comment by tianrluo** [comment]
Thanks for pointing that out!
The string is removed (v0.1.8), and the codecov token is regenerated.
